{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
     app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      {{- include "resico-rd.selectorLabels" . | nindent 8 }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end -}}

