apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hs
  labels:
    {{- include "zlb-rd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.hs_type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zlb-rd.selectorLabels" . | nindent 4 }}
